server:
  port: 8881
  servlet:
    context-path: /backend-base
  session:
    cookie:
      http-only: HttpOnly

spring:
  # data source configuration
  datasource:
    url: jdbc:mysql://localhost:3306/member?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    driver-class-ame: com.mysql.jdbc.Driver
    username: root
    password: root
    #type: com.alibaba.druid.pool.DruidDataSource
  # freemarker configuration
  freemarker:
      allow-request-override: false
      allow-session-override: false
      cache: false
      charset: UTF-8
      check-template-location: true
      content-type: text/html
      enabled: true
      expose-request-attributes: false
      expose-session-attributes: false
      expose-spring-macro-helpers: true
      prefer-file-system-access: true
      suffix: .ftl
      template-loader-path: classpath:/templates/
  resources:
      static-locations: classpath:/
  # 热启动
  devtools:
      restart:
          enabled: true
          additional-paths: src/main/java
  mvc:
      pathmatch:
          use-suffix-pattern: false
          use-registered-suffix-pattern: true
      contentnegotiation:
          favor-path-extension: false

# mybatis configuration
mybatis:
  mapper-locations: classpath*:mybatis/mapper/*Mapper.xml
  type-aliases-package: org.moonzhou.backend.base.dmo

